package ar.edu.unlam.tp0Nivelacion.enums;

public enum Competencia {
	DOCENTE,JARDIN,PRIMARIA,
	SECUNDARIA,ESPECIAL,MATEMATICA,HISTORIA,GEOGRAFIA,NO_DOCENTE,PRECEPTOR,IDIOMA,EDUCACION_FISICA,
	LITERATURA
}
