package ar.edu.unlam.tp0Nivelacion.enums;

public enum Nivel {
	CELESTE,VERDE,AZUL,ROJA,
	PRIMER_GRADO,SEGUNDO_GRADO,TERCER_GRADO,CUARTO_GRADO,QUINTO_GRADO,SEXTO_GRADO,SEPTIMO_GRADO,OCTAVO_GRADO,NOVENO_GRADO,
	PRIMER_ANIO,SEGUNDO_ANIO,TERCER_ANIO,CUARTO_ANIO,QUINTO__ANIO,SEXTO_ANIO

}
